import {
  cilDescription,
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilApplications,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSearch,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilTransfer,
  cilBrowser,
  cilSend,
  cilGroup,
  cilFolderOpen,
  cilFolder,
  cilCash,
  cilMoney,
  cil3d,
  cilLibrary,
  cilShortText,
  cilSmilePlus,
  cilLowVision,
  cilCalendarCheck,
  cilTruck,
  cilBarChart,
  cilLifeRing,
  cilChevronBottom,
  cilCaretBottom,
  cilCaretLeft,
  cilChevronCircleDownAlt,
  cilChevronCircleLeftAlt,
  cilKeyboard,
  cilEducation,
  cilLoop,
  cilColorBorder,
  cilLoopCircular,
  cilWallet,
  cilClock,
  cilBadge,
  cilShieldAlt,
  cilHappy,
  cilNoteAdd,
  cilVoiceOverRecord,
  cilWarning,
  cilCloudUpload,
  cilChartLine

} from '@coreui/icons';

export const iconSubset = {

  cilChartLine,
  cilCloudUpload,
  cilWarning,
  cilVoiceOverRecord,
  cilNoteAdd,
  cilShieldAlt,
  cilClock,
  cilWallet,
  cilColorBorder,
  cilLoop,
  cilChevronCircleLeftAlt,
  cilChevronCircleDownAlt,
  cilSmilePlus,
  cilSearch,
  cilDescription,
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplications,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilGroup,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilGrid,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLayers,
  cilList,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilTransfer,
  cilBrowser,
  cilSend,
  cilFolderOpen,
  cilFolder,
  cilCash,
  cilMoney,
  cil3d,
  cilLibrary,
  cilShortText,
  cilLowVision,
  cilCalendarCheck,
  cilTruck,
  cilBarChart,
  cilLifeRing,
  cilChevronBottom,
  cilCaretBottom,
  cilCaretLeft,
  cilKeyboard,
  cilEducation,
  cilLoopCircular,
  cilBadge,
  cilHappy
};

export enum IconSubset {

  cilChartLine = 'cilChartLine',
  cilCloudUpload = 'cilCloudUpload',
  cilWarning = 'cilWarning',
  cilVoiceOverRecord = 'cilVoiceOverRecord',
  cilNoteAdd = 'cilNoteAdd',
  cilHappy = 'cilHappy',
  cilShieldAlt = 'cilShieldAlt',
  cilBadge = 'cilBadge',
  cilClock = 'cilClock',
  cilWallet = 'cilWallet',
  cilLoopCircular = 'cilLoopCircular',
  cilColorBorder = 'cilColorBorder',
  cilLoop = 'cilLoop',
  cilApplications = 'cilApplications',
  cilChevronCircleLeftAlt = 'cilChevronCircleLeftAlt',
  cilChevronCircleDownAlt = 'cilChevronCircleDownAlt',
  cilCaretLeft = 'cilCaretLeft',
  cilCaretBottom = 'cilCaretBottom',
  cilChevronBottom = 'cilChevronBottom',
  cilLifeRing = 'cilLifeRing',
  cilBarChart = 'cilBarChart',
  cilTruck = 'cilTruck',
  cilCalendarCheck = 'cilCalendarCheck',
  cilLowVision = 'cilLowVision',
  cilSmilePlus = 'cilSmilePlus',
  cilSearch = 'cilSearch',
  cilDescription = 'cilDescription',
  cilShortText = 'cilShortText',
  cilLibrary = 'cilLibrary',
  cil3d = 'cil3d',
  cilFolder = 'cilFolder',
  cilCash = 'cilCash',
  cilMoney = 'cilMoney',
  cilFolderOpen = 'cilFolderOpen',
  cilGroup = 'cilGroup',
  cilBrowser = 'cilBrowser',
  cibCcAmex = 'cibCcAmex',
  cibCcApplePay = 'cibCcApplePay',
  cibCcMastercard = 'cibCcMastercard',
  cibCcPaypal = 'cibCcPaypal',
  cibCcStripe = 'cibCcStripe',
  cibCcVisa = 'cibCcVisa',
  cibFacebook = 'cibFacebook',
  cibGoogle = 'cibGoogle',
  cibLinkedin = 'cibLinkedin',
  cibSkype = 'cibSkype',
  cibTwitter = 'cibTwitter',
  cifBr = 'cifBr',
  cifEs = 'cifEs',
  cifFr = 'cifFr',
  cifIn = 'cifIn',
  cifPl = 'cifPl',
  cifUs = 'cifUs',
  cilAlignCenter = 'cilAlignCenter',
  cilAlignLeft = 'cilAlignLeft',
  cilAlignRight = 'cilAlignRight',
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilArrowBottom = 'cilArrowBottom',
  cilArrowRight = 'cilArrowRight',
  cilArrowTop = 'cilArrowTop',
  cilBasket = 'cilBasket',
  cilBell = 'cilBell',
  cilBold = 'cilBold',
  cilBookmark = 'cilBookmark',
  cilCalculator = 'cilCalculator',
  cilCalendar = 'cilCalendar',
  cilChart = 'cilChart',
  cilChartPie = 'cilChartPie',
  cilCheck='cilCheck',
  cilChevronLeft = 'cilChevronLeft',
  cilChevronRight = 'cilChevronRight',
  cilCloudDownload = 'cilCloudDownload',
  cilCode = 'cilCode',
  cilCommentSquare = 'cilCommentSquare',
  cilCreditCard = 'cilCreditCard',
  cilCursor = 'cilCursor',
  cilDollar = 'cilDollar',
  cilDrop = 'cilDrop',
  cilEnvelopeClosed = 'cilEnvelopeClosed',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilFile = 'cilFile',
  cilGrid = 'cilGrid',
  cilHome = 'cilHome',
  cilInbox = 'cilInbox',
  cilIndentDecrease = 'cilIndentDecrease',
  cilIndentIncrease = 'cilIndentIncrease',
  cilItalic = 'cilItalic',
  cilJustifyCenter = 'cilJustifyCenter',
  cilLayers = 'cilLayers',
  cilList = 'cilList',
  cilListNumbered = 'cilListNumbered',
  cilLocationPin = 'cilLocationPin',
  cilLockLocked = 'cilLockLocked',
  cilMagnifyingGlass = 'cilMagnifyingGlass',
  cilMap = 'cilMap',
  cilMediaPlay = 'cilMediaPlay',
  cilMenu = 'cilMenu',
  cilMoon = 'cilMoon',
  cilNotes = 'cilNotes',
  cilOptions = 'cilOptions',
  cilPaperclip = 'cilPaperclip',
  cilPaperPlane = 'cilPaperPlane',
  cilPen = 'cilPen',
  cilPencil = 'cilPencil',
  cilPeople = 'cilPeople',
  cilPrint = 'cilPrint',
  cilPuzzle = 'cilPuzzle',
  cilReportSlash = 'cilReportSlash',
  cilSend = 'cilSend',
  cilSave = 'cilSave',
  cilSettings = 'cilSettings',
  cilShare = 'cilShare',
  cilShareAll = 'cilShareAll',
  cilShareBoxed = 'cilShareBoxed',
  cilSpeech = 'cilSpeech',
  cilSpeedometer = 'cilSpeedometer',
  cilSpreadsheet = 'cilSpreadsheet',
  cilStar = 'cilStar',
  cilSun = 'cilSun',
  cilTags = 'cilTags',
  cilTask = 'cilTask',
  cilTrash = 'cilTrash',
  cilUnderline = 'cilUnderline',
  cilUser = 'cilUser',
  cilUserFemale = 'cilUserFemale',
  cilUserFollow = 'cilUserFollow',
  cilUserUnfollow = 'cilUserUnfollow',
  cilTransfer = 'cilTransfer',
  cilKeyboard = 'cilKeyboard',
  cilEducation = 'cilEducation'
}
