import { Component } from '@angular/core';
import { TechnicianPerformanceService } from './technician-performance.service';

@Component({
    selector: 'app-technician-performance',
    templateUrl: './technician-performance.component.html',
    styleUrls: ['./technician-performance.component.scss', '../../../../scss/customstyle.css'],
    standalone: false
})
export class TechnicianPerformanceComponent {
  fromDate: any = '';
  toDate: any = '';
  siteTypeId: any = 'Select Site Type';
  techId: any = 'Select Technician';
  techName: any;
  branchCode: any = 'Select Branch';
  productFamily: any = 'Select Product Family';
  branchListTemp: any = [];
  serviceTypeList: any = [];
  branchList: any = [];
  technicians: any = [];
  productFamilies: any = [];
  legendsLIst: any = [];
  legendListTemp: any = [];
  showTable = false;
  showInnerTable = false;
  showProductList = false;
  totalCount: any = [];
  performanceData: any;
  totalPoints: any = [];
  branchTechnicians: any = [];
  branchesListData: any = [];
  techniciansData: any = [];
  branchesListTemp: any = [];
  productValue: any = [];
  techniciansProduct: any = [];
  productWiseLegend: any = [];
  errorMessage: any = '';
  loading = false;
  expanded = false;
  tooltipValues: any = [];
  tooltipValuesOnsite: any =[]
  showNoData = false;

  constructor(public dataService: TechnicianPerformanceService) {
    this.getOptions();
    this.getBranches();
    this.tooltipValues = [{value: 'Device Delivered', code: 'DD'},{value: 'In Repair', code: 'INRP'},{value: 'On hold - customer approval and payment awaited', code: 'OHCAPA'},{value: 'On hold - L1 approval required to proceed', code: 'OHL1'},{value: 'On hold - L2 approval required to proceed', code: 'OHL2'},{value: 'Parts arrived from DC - to be inwarded', code: 'DCIN'},{value: 'Parts arrived from RC - to be inwarded', code: 'RCIN'},{value: 'Product Accepted - To be diagnosed', code: 'PATBD'},{value: 'QC - L1 Approval pending (CIN)', code: 'QCL1'},{value: 'QC - L1 Approval pending (SVNR)', code: 'QCL1SVNR'},{value: 'QC - L1 Approval Pending (WUMS)', code: 'QCL1WUMS'},
                          {value: 'Ready for pickup', code: 'RFPU'},{value: 'Requote generated by RC - Pending customer approval', code: 'RGPCA'},{value: 'Shipment Ready for RC & awaiting pick up by shipper', code: 'RCOUT'},{value: 'Token to be accepted', code: 'TTBA'},{value: 'Device Pick Up Scheduled', code: 'DPUS'},{value: 'Units to be Replaced', code: 'UTBR'},{value: 'Pending Site/DL Delivery', code: 'PSDD'}, {value: 'Device In Transit', code: 'DINT'}];
    this.tooltipValuesOnsite = [{value: 'Ticket Closed', code: 'TC'}, {value: 'KBB shipped to DC - To be inwarded at Apple', code: 'KSDCTIA'}, {value: 'KBB collected - To be shipped', code: 'KCTS'}, {value: 'Pending KBB collection from Customer', code: 'PKCFC'}, {value: 'Repair Marked Complete', code: 'RMC'}, {value: 'Ready for Pickup ', code: 'RFPU'}, {value: 'In Repair', code: 'IR'}, {value: 'Spares delivered - Technician Scheduled', code: 'SDTS'}, {value: 'Invoice / DC generated - pending technician to be scheduled', code: 'IGPTS'}, {value: 'Spares Inwarded - Pending Invoice (OOW) and DC', code: 'SIPIOOW'}, {value: 'Spares Received - to be Inwarded', code: 'SRTI'}, {value: 'Repair Declined by Apple', code: 'RDBA'}, {value: 'On Hold - Parts Contraint', code: 'OHPC'}, {value: 'Repair Approved - Awaiting Spares', code: 'RAAS'},
    {value: 'On Hold - L2 Approval', code: 'OHL2'}, {value: 'OPF Appoved - Spares to be Ordered', code: 'OASTO'}, {value: 'PO Received - Awaiting OPF Approval', code: 'PRAO'}, {value: 'Quote shared - Awaiting PO', code: 'QSAPO'}, {value: 'On Hold - L1 Approval ', code: 'OHL1'}, {value: 'On Hold - Quote to be shared (OOW)', code: 'OHQSOOW'}, {value: 'Under Diagnosis', code: 'UD'}, {value: 'Ticket assigned and scheduled - To be visited', code: 'TATV'}, {value: 'Ticket Validated - To be Scheduled', code: 'TVTS'}, {value: 'New Ticket - to be Validate', code: 'NTBV'}];
    // this.productFamilies = [{ name: 'iPod', value: 'IPOD' }, { name: 'iPad', value: 'IPAD' }, { name: 'iPhone', value: 'IPHONE' }, { name: 'Watch', value: 'WATCH' }, { name: 'Apple TV', value: 'APPLETV' }, { name: 'Mac', value: 'MAC' }, { name: 'Beats', value: 'BEATS' },];
  }

  getBranches() {
    let result;
    this.dataService.getOptions()
      .subscribe({
        next: (data: any) => {
          result = data;
          this.productFamilies = result.family;
        }, // success path
        error: error => error = error // error path
      });
  }

  getOptions() {
    let result;
    this.dataService.getBranches()
      .subscribe({
        next: (data: any) => {
          result = data;
          this.branchListTemp = result.branch;
          this.serviceTypeList = result.sitetype;
        }, // success path
        error: error => error = error // error path
      });
  }

  load() {
    this.errorMessage = '';
    if (this.branchCode === 'Select Branch' || this.techId === 'Select Technician' || this.siteTypeId === 'Select Site Type' || this.productFamily === 'Select Product Family' || this.fromDate === '' || this.toDate === '') {
      this.errorMessage = 'Please Fill all Mandatory Fields';
      return;
    } else if (this.fromDate > this.toDate) {
      this.errorMessage = 'From Date cannot be greater than To Date';
      return;
    } else {
      this.techniciansData = [];
      this.branchesListData = [];
      this.branchesListTemp = [];
      this.legendListTemp = [];
      this.legendsLIst = [];
      this.showTable = false;
      this.showNoData = false;
      this.totalCount = [];
      this.totalPoints = [];
      /* if(this.productFamily !== '') {
        this.productFamilies = this.productFamilies.filter((x: any) => x.value === this.productFamily);
      } */
      this.getPerformanceData();
    }
  }

  getPerformanceData() {
    let result: any;
    this.loading = true;
    this.dataService.getPerformanceData(this.fromDate, this.toDate, this.siteTypeId, this.techId, this.branchCode, this.productFamily)
      .subscribe({
        next: (data: any) => {
          result = data;
          if(result.length > 0) {
          this.performanceData = result;
          for (let i = 0; i < result.length; i++) {
            if(result[i].user_branch_code) {
              if(result[i].group_id !== '2' && (result[i].user_branch_code !== '' && result[i].user_branch_code !== null)) {
                result[i].branch_code = result[i].user_branch_code;
                this.performanceData[i].branch_code = this.performanceData[i].user_branch_code;
              }
            }
            this.legendListTemp.push(result[i].legend);
            this.branchesListTemp.push(result[i].branch_code);
            this.techniciansData.push({
              id: result[i].technician_id,
              branch: result[i].branch_code,
              name: result[i].technician_name,
              role: result[i].group_name
            });
          }
          this.legendListTemp = this.legendListTemp.filter(function (elem: any, index: any, self: any) {
            return index === self.indexOf(elem);
          });
          this.branchesListTemp = this.branchesListTemp.filter(function (elem: any, index: any, self: any) {
            return index === self.indexOf(elem);
          });
          this.techniciansData = this.techniciansData.filter((value: any, index: any) => this.techniciansData.indexOf(value) === index);
          for (let i = 0; i < this.branchesListTemp.length; i++) {
            let branchBinCount: any = 0;
            let branchBinPoint: any = 0;
            let branchWiseLegend = [];
            let branchDetails = this.branchListTemp.filter((branchCode: any) => {
              return (branchCode.branch_code === this.branchesListTemp[i])
            });
            if (branchDetails.length > 0) {
              for (let bins = 0; bins < this.legendListTemp.length; bins++) {
                let branchBins = this.performanceData.filter((count: any) => {
                  return ((count.legend === this.legendListTemp[bins] && count.branch_code === branchDetails[0].branch_code))
                });
                if (branchBins.length > 0) {
                  branchBinCount = 0;
                  branchBinPoint = 0;
                  for (let bin = 0; bin < branchBins.length; bin++) {
                    if(branchBins[bin].bin_points === '0') {
                      branchBins[bin].count = 0;
                    }
                    branchBinCount = +branchBinCount + +branchBins[bin].count;
                    branchBinPoint = +branchBinPoint + +branchBins[bin].bin_points;
                  }
                  branchWiseLegend.push(branchBinCount);
                  branchWiseLegend.push(branchBinPoint);
                } else {
                  branchWiseLegend.push(0);
                  branchWiseLegend.push(0);
                }
              }
              this.branchesListData.push({
                name: branchDetails[0].branch_name,
                branchCode: branchDetails[0].branch_code,
                branchBins: branchWiseLegend
              });
            }
          }
          for (let i = 0; i < this.legendListTemp.length; i++) {
            this.legendsLIst.push(this.legendListTemp[i]);
            this.legendsLIst.push(this.legendListTemp[i]);
          }
          this.showTable = true;
          for (let i = 0; i < this.branchesListData.length; i++) {
            let branchCount: any;
            let count: any = 0;
            let point: any = 0;
            branchCount = this.performanceData.filter((branchCode: any) => {
              return (branchCode.branch_code === this.branchesListData[i].branchCode)
            });
            for (let j = 0; j < branchCount.length; j++) {
              if(branchCount[j].bin_points === '0') {
                branchCount[j].count = 0;
              }
              count = +count + +branchCount[j].count;
              point = +point + +branchCount[j].bin_points;
            }
            this.totalCount.push(count);
            this.totalPoints.push(point);
          }
          for (let i = 0; i < this.techniciansData.length; i++) {
            let techCount: any = 0;
            let techPoint: any = 0;
            this.productValue = [];
            let totalProdCount: any = 0;
            let totalProdPoint: any = 0;
            let productWiseLegend: any = [];
            let Count = this.performanceData.filter((count: any) => {
              return (count.technician_id === this.techniciansData[i].id && count.branch_code === this.techniciansData[i].branch)
            });
            for (let p = 0; p < this.productFamilies.length; p++) {
              let prodCount: any = 0;
              let prodPoint: any = 0;
              let products = this.performanceData.filter((count: any) => {
                return (count.technician_id === this.techniciansData[i].id && count.branch_code === this.techniciansData[i].branch && count.family_name === this.productFamilies[p].value)
              });
              if (products.length > 0) {
                for (let m = 0; m < products.length; m++) {
                  productWiseLegend = [];
                  prodCount = +prodCount + +products[m].count;
                  prodPoint = +prodPoint + +products[m].bin_points;
                  for (let bins = 0; bins < this.legendListTemp.length; bins++) {
                    let binCount = 0;
                    let binPoint = 0;
                    let techBins = products.filter((count: any) => {
                      return (count.legend === this.legendListTemp[bins])
                    });
                    if (techBins.length > 0) {
                      for (let bin = 0; bin < techBins.length; bin++) {
                        if(techBins[bin].bin_points === '0') {
                          techBins[bin].count = 0;
                        }
                        binCount = +binCount + +techBins[bin].count;
                        binPoint = +binPoint + +techBins[bin].bin_points;
                      }
                      productWiseLegend.push(binCount);
                      productWiseLegend.push(binPoint);
                    } else {
                      productWiseLegend.push(0);
                      productWiseLegend.push(0);
                    }
                  }
                }
              } else {
                productWiseLegend = [];
                for (let k = 0; k < this.legendListTemp.length; k++) {
                  productWiseLegend.push(0);
                  productWiseLegend.push(0);
                }
              }
              this.productValue.push({
                count: prodCount,
                point: prodPoint,
                family: this.productFamilies[p].value,
                techId: this.techniciansData[i].id,
                binCountPoint: productWiseLegend
              })
              totalProdCount = +totalProdCount + +prodCount;
              totalProdPoint = +totalProdPoint + +prodPoint;
            }

            for (let j = 0; j < Count.length; j++) {
              if(Count[j].bin_points === '0') {
                Count[j].count = 0;
              }
              techCount = +techCount + +Count[j].count;
              techPoint = +techPoint + +Count[j].bin_points;
            }
            let techLegendTotal: any = [];
            for (let techBins = 0; techBins < this.legendListTemp.length; techBins++) {
              let techBinTotal = this.performanceData.filter((count: any) => {
                return (count.technician_id === this.techniciansData[i].id && count.branch_code === this.techniciansData[i].branch && count.legend === this.legendListTemp[techBins])
              });
              let techLegendCount = 0;
              let techLegendPoint = 0;
              if (techBinTotal.length > 0) {
                for (let bin = 0; bin < techBinTotal.length; bin++) {
                  if(techBinTotal[bin].bin_points === '0') {
                    techBinTotal[bin].count = 0;
                  }
                  techLegendCount = +techLegendCount + +techBinTotal[bin].count;
                  techLegendPoint = +techLegendPoint + +techBinTotal[bin].bin_points;
                }
                techLegendTotal.push(techLegendCount);
                techLegendTotal.push(techLegendPoint);
              } else {
                techLegendTotal.push(0);
                techLegendTotal.push(0);
              }
            }

            this.techniciansData[i].techCount = techCount;
            this.techniciansData[i].techPoint = techPoint;
            this.techniciansData[i].prodPoint = totalProdPoint;
            this.techniciansData[i].prodCount = totalProdCount;
            this.techniciansData[i].productsValue = this.productValue;
            this.techniciansData[i].binsTotal = techLegendTotal;
            // this.techniciansData[i].productsValue.productBins = productWiseLegend;
          }
          this.loading = false;
          } else {
            this.loading = false;
            this.showTable = false;
            this.showNoData = true;
          }
        }, // success path
        error: (error: any) => error // error path
      });
  }

  siteTypeSelected(event: string) {
    this.branchCode = 'Select Branch';
    this.techId = 'Select Technician';
    this.branchList = [];
    if (event === '1') {
      this.branchList = this.branchListTemp.filter((branchCode: any) => {
        return (branchCode.branch_type === 'I' || branchCode.branch_type === 'A' || branchCode.branch_type === 'D' )
      });
    } else if (event === '2') {
      this.branchList = this.branchListTemp.filter((branchCode: any) => {
        return (branchCode.branch_type === 'O')
      });
    }
  }

  branchSelected(event: string) {
    this.techId = 'Select Technician';
    this.dataService.getTechnicians(event)
      .subscribe({
        next: (data: any) => {
          const techData: any = data;
          this.technicians = techData.user;
        }, // success path
        error: (error: any) => error = error // error path
      });
  }

  expandBranch(i: any, branch: any, action: any) {
    this.expanded = false;
    if (action === 'open') {
      let opnedBranch = this.branchesListData.find((opened: any) => {
        return (opened.showInnerTable === true)
      });
      if (opnedBranch !== undefined) {
        opnedBranch.showInnerTable = false;
      }

      this.branchesListData[i].showInnerTable = true;
      let techArray = this.techniciansData.filter((tech: any) => {
        return (tech.branch === branch)
      });

      this.branchTechnicians = techArray.filter((obj: any, pos: any, arr: any) => {
        return arr.map((mapObj: any) => mapObj['id']).indexOf(obj['id']) === pos;
      });
    } else if (action === 'close') {
      this.branchesListData[i].showInnerTable = false;
    }
  }

  expandTech(j: any, id: any, action: any) {
    if (action === 'open') {
      this.expanded = true;
      let openedTech = this.branchTechnicians.find((opened: any) => {
        return (opened.showProductList === true)
      });
      if (openedTech !== undefined) {
        openedTech.showProductList = false;
      }
      this.branchTechnicians[j].showProductList = true;
      this.techniciansProduct = this.branchTechnicians.filter((tech: any) => {
        return (tech.id === id)
      });
      this.techniciansProduct = this.techniciansProduct[0].productsValue;
      this.techniciansProduct.backgroundColor = 'red';
    } else if (action === 'close') {
      this.expanded = false;
      this.branchTechnicians[j].showProductList = false;
    }
  }
}
